import {CommonModule} from '@angular/common'; import {Component,computed,inject,signal} from '@angular/core'; import {FormsModule} from '@angular/forms'; import {Task,TaskPriority,TaskStatus,Subtask} from './models/task.model'; import {TaskService} from './services/task.service';
@Component({selector:'app-root',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./app.component.html',styleUrl:'./app.component.css'}) export class AppComponent{
 store=inject(TaskService); page=signal<'dashboard'|'tasks'|'calendar'|'stats'|'trash'|'settings'>('tasks'); view=signal<'kanban'|'list'>('kanban'); showForm=signal(false); editingId=signal<string|null>(null); dark=signal(localStorage.getItem('todo.dark')==='1'); toast=signal(''); dragId=''; search=''; filterStatus='all'; filterPriority='all'; filterProject='all'; sort='manual'; focusTask=signal<Task|null>(null); timerSeconds=signal(0); timer:any;
 form:any={}; subtasks:Subtask[]=[]; newSub=''; tagText=''; linkText='';
 total=computed(()=>this.store.tasks().filter(t=>!t.archived).length); done=computed(()=>this.store.tasks().filter(t=>t.status==='done'&&!t.archived).length); progress=computed(()=>this.total()?Math.round(this.done()/this.total()*100):0); overdue=computed(()=>this.store.tasks().filter(t=>this.isOverdue(t)).length); today=computed(()=>new Date().toISOString().slice(0,10));
 projects=computed(()=>[...new Set(this.store.tasks().map(t=>t.project).filter(Boolean))]); categories=computed(()=>[...new Set(this.store.tasks().map(t=>t.category).filter(Boolean))]);
 filtered=()=>{let a=this.store.tasks().filter(t=>!t.archived); const q=this.search.toLowerCase().trim(); if(q)a=a.filter(t=>[t.title,t.description,t.notes,t.project,t.category,...t.tags].join(' ').toLowerCase().includes(q)); if(this.filterStatus!=='all')a=a.filter(t=>t.status===this.filterStatus); if(this.filterPriority!=='all')a=a.filter(t=>t.priority===this.filterPriority); if(this.filterProject!=='all')a=a.filter(t=>t.project===this.filterProject); const rank:any={urgent:0,high:1,normal:2,low:3,none:4}; return [...a].sort((x,y)=>this.sort==='due'?(x.dueDate||'9999').localeCompare(y.dueDate||'9999'):this.sort==='priority'?rank[x.priority]-rank[y.priority]:this.sort==='name'?x.title.localeCompare(y.title):Number(y.pinned)-Number(x.pinned));};
 projectCount(p:string){return this.filtered().filter(t=>t.project===p).length} subDone(){return this.store.tasks().reduce((n,t)=>n+t.subtasks.filter(s=>s.completed).length,0)}
 byStatus(s:TaskStatus){return this.filtered().filter(t=>t.status===s)} subProgress(t:Task){return t.subtasks.length?Math.round(t.subtasks.filter(s=>s.completed).length/t.subtasks.length*100):(t.completed?100:0)} isOverdue(t:Task){return !!t.dueDate&&t.status!=='done'&&t.dueDate<this.today()} dueLabel(t:Task){if(!t.dueDate)return ''; if(t.dueDate===this.today())return "Aujourd’hui"; return new Intl.DateTimeFormat('fr-BE').format(new Date(t.dueDate+'T12:00:00'))}
 setPage(p:any){this.page.set(p)} toggleDark(){this.dark.update(v=>!v);localStorage.setItem('todo.dark',this.dark()?'1':'0')}
 openCreate(status:TaskStatus='todo'){this.editingId.set(null);this.form={title:'',description:'',notes:'',status,priority:'normal',startDate:'',dueDate:'',dueTime:'',estimatedMinutes:0,spentMinutes:0,category:'',project:'',favorite:false,pinned:false,archived:false,color:'#ffffff',recurrence:'none',reminder:'',dependencies:[]};this.subtasks=[];this.tagText='';this.linkText='';this.showForm.set(true)}
 openEdit(t:Task){this.editingId.set(t.id);this.form={...t};this.subtasks=t.subtasks.map(s=>({...s}));this.tagText=t.tags.join(', ');this.linkText=t.links.join('\n');this.showForm.set(true)}
 addSub(){if(!this.newSub.trim())return;this.subtasks.push({id:crypto.randomUUID(),title:this.newSub.trim(),completed:false,priority:'normal'});this.newSub=''} removeSub(id:string){this.subtasks=this.subtasks.filter(s=>s.id!==id)}
 save(){if(!this.form.title?.trim())return this.notify('Ajoute un titre.'); const all=this.subtasks.length>0&&this.subtasks.every(s=>s.completed); const data={...this.form,title:this.form.title.trim(),subtasks:[...this.subtasks],tags:this.tagText.split(',').map((x:string)=>x.trim()).filter(Boolean),links:this.linkText.split('\n').map((x:string)=>x.trim()).filter(Boolean),status:all?'done':this.form.status,completed:all||this.form.status==='done'};this.store.save(data,this.editingId()||undefined);this.showForm.set(false);this.notify(this.editingId()?'Tâche modifiée.':'Tâche créée.')}
 drop(e:DragEvent,s:TaskStatus){e.preventDefault();if(this.dragId)this.store.moveTask(this.dragId,s);this.dragId=''} archive(t:Task){this.store.save({archived:!t.archived},t.id)} favorite(t:Task){this.store.save({favorite:!t.favorite},t.id)} pin(t:Task){this.store.save({pinned:!t.pinned},t.id)} remove(t:Task){if(confirm(`Mettre « ${t.title} » dans la corbeille ?`))this.store.remove(t.id)}
 exportJson(){this.download(new Blob([JSON.stringify({version:3,tasks:this.store.tasks()},null,2)],{type:'application/json'}),'todolist-backup.json')} importJson(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));this.store.replaceTasks(Array.isArray(x)?x:x.tasks);this.notify('Sauvegarde restaurée.')}catch{this.notify('Fichier invalide.')}};r.readAsText(f)} exportCsv(){const rows=[['Titre','Statut','Priorité','Projet','Catégorie','Échéance','Progression'],...this.store.tasks().map(t=>[t.title,t.status,t.priority,t.project,t.category,t.dueDate,String(this.subProgress(t))])];this.download(new Blob(['\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n')],{type:'text/csv'}),'todolist.csv')} print(){window.print()}
 startFocus(t:Task){this.focusTask.set(t);this.timerSeconds.set(25*60);clearInterval(this.timer);this.timer=setInterval(()=>{if(this.timerSeconds()>0)this.timerSeconds.update(v=>v-1);else clearInterval(this.timer)},1000)} stopFocus(){clearInterval(this.timer);const t=this.focusTask();if(t){const mins=Math.max(1,Math.round((25*60-this.timerSeconds())/60));this.store.save({spentMinutes:t.spentMinutes+mins},t.id)}this.focusTask.set(null)} timerText(){const s=this.timerSeconds();return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
 notify(m:string){this.toast.set(m);setTimeout(()=>this.toast.set(''),2200)} download(b:Blob,n:string){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)} formatDate(v:string){return new Intl.DateTimeFormat('fr-BE',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}
}
