import {CommonModule} from '@angular/common'; import {Component,computed,inject,signal} from '@angular/core'; import {FormsModule} from '@angular/forms'; import {Task,TaskPriority,TaskStatus,Subtask} from './models/task.model'; import {TaskService} from './services/task.service';
@Component({selector:'app-root',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./app.component.html',styleUrl:'./app.component.css'}) export class AppComponent{
 store=inject(TaskService); page=signal<'dashboard'|'tasks'|'calendar'|'stats'|'trash'|'settings'>('tasks'); view=signal<'kanban'|'list'>('kanban'); showForm=signal(false); editingId=signal<string|null>(null); dark=signal(localStorage.getItem('todo.dark')==='1'); toast=signal(''); dragId=''; search=''; filterStatus='all'; filterPriority='all'; filterProject='all'; sort='manual'; focusTask=signal<Task|null>(null); timerSeconds=signal(0); timer:any;
 form:any={}; subtasks:Subtask[]=[]; newSub=''; tagText=''; linkText='';
 total=computed(()=>this.store.tasks().filter(t=>!t.archived).length); done=computed(()=>this.store.tasks().filter(t=>t.status==='done'&&!t.archived).length); progress=computed(()=>this.total()?Math.round(this.done()/this.total()*100):0); overdue=computed(()=>this.store.tasks().filter(t=>this.isOverdue(t)).length); today=computed(()=>new Date().toISOString().slice(0,10));
 projects=computed(()=>[...new Set(this.store.tasks().map(t=>t.project).filter(Boolean))]); categories=computed(()=>[...new Set(this.store.tasks().map(t=>t.category).filter(Boolean))]);
 filtered=()=>{let a=this.store.tasks().filter(t=>!t.archived); const q=this.search.toLowerCase().trim(); if(q)a=a.filter(t=>[t.title,t.description,t.notes,t.project,t.category,...t.tags].join(' ').toLowerCase().includes(q)); if(this.filterStatus!=='all')a=a.filter(t=>t.status===this.filterStatus); if(this.filterPriority!=='all')a=a.filter(t=>t.priority===this.filterPriority); if(this.filterProject!=='all')a=a.filter(t=>t.project===this.filterProject); const rank:any={urgent:0,high:1,normal:2,low:3,none:4}; return [...a].sort((x,y)=>this.sort==='due'?(x.dueDate||'9999').localeCompare(y.dueDate||'9999'):this.sort==='priority'?rank[x.priority]-rank[y.priority]:this.sort==='name'?x.title.localeCompare(y.title):Number(y.pinned)-Number(x.pinned));};
 projectCount(p:string){return this.filtered().filter(t=>t.project===p).length} subDone(){return this.store.tasks().reduce((n,t)=>n+t.subtasks.filter(s=>s.completed).length,0)}
 byStatus(s:TaskStatus){return this.filtered().filter(t=>t.status===s)} subProgress(t:Task){return t.subtasks.length?Math.round(t.subtasks.filter(s=>s.completed).length/t.subtasks.length*100):(t.completed?100:0)} isOverdue(t:Task){return !!t.dueDate&&t.status!=='done'&&t.dueDate<this.today()} dueLabel(t:Task){if(!t.dueDate)return ''; if(t.dueDate===this.today())return "Aujourd’hui"; return new Intl.DateTimeFormat('fr-BE').format(new Date(t.dueDate+'T12:00:00'))}
 setPage(p:any){this.page.set(p)} toggleDark(){this.dark.update(v=>!v);localStorage.setItem('todo.dark',this.dark()?'1':'0')}
 openCreate(status:TaskStatus='todo'){this.editingId.set(null);this.form={title:'',description:'',notes:'',status,priority:'normal',startDate:'',dueDate:'',dueTime:'',estimatedMinutes:0,spentMinutes:0,category:'',project:'',favorite:false,pinned:false,archived:false,color:'#ffffff',recurrence:'none',reminder:'',dependencies:[]};this.subtasks=[];this.tagText='';this.linkText='';this.showForm.set(true)}
 openEdit(t:Task){this.editingId.set(t.id);this.form={...t};this.subtasks=t.subtasks.map(s=>({...s}));this.tagText=t.tags.join(', ');this.linkText=t.links.join('\n');this.showForm.set(true)}
 addSub(){if(!this.newSub.trim())return;this.subtasks.push({id:crypto.randomUUID(),title:this.newSub.trim(),completed:false,priority:'normal'});this.newSub=''} removeSub(id:string){this.subtasks=this.subtasks.filter(s=>s.id!==id)}
 save(){if(!this.form.title?.trim())return this.notify('Ajoute un titre.'); const all=this.subtasks.length>0&&this.subtasks.every(s=>s.completed); const data={...this.form,title:this.form.title.trim(),subtasks:[...this.subtasks],tags:this.tagText.split(',').map((x:string)=>x.trim()).filter(Boolean),links:this.linkText.split('\n').map((x:string)=>x.trim()).filter(Boolean),status:all?'done':this.form.status,completed:all||this.form.status==='done'};this.store.save(data,this.editingId()||undefined);this.showForm.set(false);this.notify(this.editingId()?'Tâche modifiée.':'Tâche créée.')}
 drop(e:DragEvent,s:TaskStatus){e.preventDefault();if(this.dragId)this.store.moveTask(this.dragId,s);this.dragId=''} archive(t:Task){this.store.save({archived:!t.archived},t.id)} favorite(t:Task){this.store.save({favorite:!t.favorite},t.id)} pin(t:Task){this.store.save({pinned:!t.pinned},t.id)} remove(t:Task){if(confirm(`Mettre « ${t.title} » dans la corbeille ?`))this.store.remove(t.id)}
 exportWord(){const tasks=this.filtered();const rows=tasks.map(t=>`<tr><td><b>${this.escapeHtml(t.title)}</b>${t.description?`<div class="desc">${this.escapeHtml(t.description)}</div>`:''}</td><td>${this.statusLabel(t.status)}</td><td>${this.priorityLabel(t.priority)}</td><td>${this.escapeHtml(t.project||'—')}</td><td>${this.escapeHtml(t.dueDate?this.dueLabel(t):'—')}</td><td>${this.subProgress(t)}%</td></tr>`).join('');const html=`<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:1.5cm}body{font-family:Arial,sans-serif;color:#2b171b}h1{color:#a51f32;text-align:center;margin-bottom:4px}.sub{text-align:center;color:#766368;margin-bottom:28px}table{width:100%;border-collapse:collapse;font-size:10pt}th{background:#a51f32;color:white;padding:9px;text-align:left}td{padding:9px;border-bottom:1px solid #eadde0;vertical-align:top}.desc{font-size:8.5pt;color:#766368;margin-top:4px}.foot{margin-top:22px;text-align:center;color:#8a777b;font-size:8pt}</style></head><body><h1>Mes tâches</h1><div class="sub">Liste générée le ${new Intl.DateTimeFormat('fr-BE',{dateStyle:'long'}).format(new Date())} · ${tasks.length} tâche(s)</div><table><thead><tr><th>Tâche</th><th>Statut</th><th>Priorité</th><th>Projet</th><th>Date</th><th>Progression</th></tr></thead><tbody>${rows}</tbody></table><div class="foot">TASKFLOW · Liste de tâches</div></body></html>`;this.download(new Blob(['\ufeff',html],{type:'application/msword'}),'mes-taches.doc')}
 exportPdf(){const tasks=this.filtered();const lines:string[]=[];lines.push('MES TACHES');lines.push(`Liste generee le ${new Intl.DateTimeFormat('fr-BE').format(new Date())} - ${tasks.length} tache(s)`);lines.push('');for(const t of tasks){lines.push(`${t.title} | ${this.statusLabel(t.status)} | ${this.priorityLabel(t.priority)}`);lines.push(`Projet: ${t.project||'-'} | Date: ${t.dueDate?this.dueLabel(t):'-'} | Progression: ${this.subProgress(t)}%`);if(t.description)lines.push(`Note: ${t.description}`);lines.push('------------------------------------------------------------')}const blob=this.makePdf(lines);this.download(blob,'mes-taches.pdf')}
 makePdf(lines:string[]){const esc=(v:string)=>v.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');const wrap=(v:string,n=88)=>{const words=v.split(/\s+/);const out:string[]=[];let line='';for(const w of words){if((line+' '+w).trim().length>n){if(line)out.push(line);line=w}else line=(line+' '+w).trim()}if(line)out.push(line);return out};const all=lines.flatMap(x=>wrap(x));const pages:Array<string[]>=[];for(let i=0;i<all.length;i+=43)pages.push(all.slice(i,i+43));if(!pages.length)pages.push(['Aucune tache.']);const objs:string[]=[];const add=(x:string)=>{objs.push(x);return objs.length};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');const bold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');const pageIds:number[]=[];const contentIds:number[]=[];for(const pg of pages){let c='BT\n/F1 10 Tf\n50 790 Td\n14 TL\n';pg.forEach((line,i)=>{if(i===0)c+='/F2 17 Tf\n';else if(i===1)c+='/F1 9 Tf\n';else if(i===2)c+='/F1 10 Tf\n';c+=`(${esc(line)}) Tj\nT*\n`});c+='ET';contentIds.push(add(`<< /Length ${c.length} >>\nstream\n${c}\nendstream`));pageIds.push(add('PENDING'))}const pagesId=objs.length+1;add(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`);pageIds.forEach((id,i)=>objs[id-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`);const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);let pdf='%PDF-1.4\n';const offsets=[0];for(let i=0;i<objs.length;i++){offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${objs[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objs.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;const bytes=new Uint8Array(pdf.length);for(let i=0;i<pdf.length;i++){let code=pdf.charCodeAt(i);if(code>255)code=63;bytes[i]=code}return new Blob([bytes],{type:'application/pdf'})}
 escapeHtml(v:string){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))} statusLabel(s:string){return ({todo:'À faire',doing:'En cours',waiting:'En attente',blocked:'Bloquée',done:'Terminée',cancelled:'Annulée'} as any)[s]||s} priorityLabel(p:string){return ({none:'Aucune',low:'Basse',normal:'Normale',high:'Haute',urgent:'Urgente'} as any)[p]||p}
 exportJson(){this.download(new Blob([JSON.stringify({version:3,tasks:this.store.tasks()},null,2)],{type:'application/json'}),'todolist-backup.json')} importJson(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));this.store.replaceTasks(Array.isArray(x)?x:x.tasks);this.notify('Sauvegarde restaurée.')}catch{this.notify('Fichier invalide.')}};r.readAsText(f)} exportCsv(){const rows=[['Titre','Statut','Priorité','Projet','Catégorie','Échéance','Progression'],...this.store.tasks().map(t=>[t.title,t.status,t.priority,t.project,t.category,t.dueDate,String(this.subProgress(t))])];this.download(new Blob(['\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n')],{type:'text/csv'}),'todolist.csv')} print(){window.print()}
 startFocus(t:Task){this.focusTask.set(t);this.timerSeconds.set(25*60);clearInterval(this.timer);this.timer=setInterval(()=>{if(this.timerSeconds()>0)this.timerSeconds.update(v=>v-1);else clearInterval(this.timer)},1000)} stopFocus(){clearInterval(this.timer);const t=this.focusTask();if(t){const mins=Math.max(1,Math.round((25*60-this.timerSeconds())/60));this.store.save({spentMinutes:t.spentMinutes+mins},t.id)}this.focusTask.set(null)} timerText(){const s=this.timerSeconds();return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
 notify(m:string){this.toast.set(m);setTimeout(()=>this.toast.set(''),2200)} download(b:Blob,n:string){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)} formatDate(v:string){return new Intl.DateTimeFormat('fr-BE',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}
}
