import { Injectable,effect,signal } from '@angular/core';
import { Subtask,Task,TaskStatus } from '../models/task.model';
const K='taskflow.tasks.ultra', T='taskflow.trash.ultra';
@Injectable({providedIn:'root'}) export class TaskService {
 tasks=signal<Task[]>(this.read(K)); trash=signal<Task[]>(this.read(T));
 constructor(){ effect(()=>localStorage.setItem(K,JSON.stringify(this.tasks()))); effect(()=>localStorage.setItem(T,JSON.stringify(this.trash()))); localStorage.removeItem('taskflow.history.ultra'); }
 save(task:Partial<Task>, id?:string){ const now=new Date().toISOString(); if(id){ const old=this.tasks().find(t=>t.id===id); if(!old)return; const next=this.normalize({...old,...task,id,updatedAt:now}); this.tasks.update(a=>a.map(t=>t.id===id?next:t)); } else { const next=this.normalize({...task,id:crypto.randomUUID(),createdAt:now,updatedAt:now}); this.tasks.update(a=>[next,...a]); } }
 duplicate(id:string){ const t=this.tasks().find(x=>x.id===id); if(!t)return; this.save({...t,id:undefined,title:t.title+' (copie)',subtasks:t.subtasks.map(s=>({...s,id:crypto.randomUUID()}))}); }
 toggleSubtask(tid:string,sid:string){ const t=this.tasks().find(x=>x.id===tid); if(!t)return; const subs=t.subtasks.map(s=>s.id===sid?{...s,completed:!s.completed}:s); const all=subs.length>0&&subs.every(s=>s.completed); const some=subs.some(s=>s.completed); this.save({subtasks:subs,status:all?'done':some?'doing':t.status==='done'?'todo':t.status,completed:all},tid); }
 moveTask(id:string,status:TaskStatus){ const t=this.tasks().find(x=>x.id===id); if(!t)return; this.save({status,completed:status==='done',subtasks:status==='done'?t.subtasks.map(s=>({...s,completed:true})):t.subtasks},id); }
 remove(id:string){ const t=this.tasks().find(x=>x.id===id); if(!t)return; this.trash.update(a=>[t,...a]); this.tasks.update(a=>a.filter(x=>x.id!==id)); }
 restore(id:string){ const t=this.trash().find(x=>x.id===id); if(!t)return; this.tasks.update(a=>[t,...a]); this.trash.update(a=>a.filter(x=>x.id!==id)); }
 purge(id:string){this.trash.update(a=>a.filter(x=>x.id!==id));} emptyTrash(){this.trash.set([])}
 replaceTasks(a:Task[]){this.tasks.set(a.map(x=>this.normalize(x)))}
 private read(key:string):Task[]{try{const a=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(a)?a.map(x=>this.normalize(x)):[]}catch{return[]}}
 private normalize(v:any):Task { const now=new Date().toISOString(); const subtasks:Array<Subtask>=Array.isArray(v?.subtasks)?v.subtasks.map((s:any)=>({id:s.id||crypto.randomUUID(),title:String(s.title||'Sous-tâche'),completed:!!s.completed,priority:s.priority||'normal',dueDate:s.dueDate||''})):[]; const all=subtasks.length>0&&subtasks.every(s=>s.completed); const status:TaskStatus=all?'done':(['todo','doing','done','waiting','blocked','cancelled'].includes(v?.status)?v.status:(v?.completed?'done':'todo')); return {id:v?.id||crypto.randomUUID(),title:String(v?.title||'Sans titre'),description:v?.description||'',notes:v?.notes||'',completed:status==='done',status,priority:v?.priority||'normal',subtasks,createdAt:v?.createdAt||now,updatedAt:v?.updatedAt||now,startDate:v?.startDate||'',dueDate:v?.dueDate||'',dueTime:v?.dueTime||'',estimatedMinutes:Number(v?.estimatedMinutes)||0,spentMinutes:Number(v?.spentMinutes)||0,category:v?.category||'',project:v?.project||'',tags:Array.isArray(v?.tags)?v.tags:[],favorite:!!v?.favorite,pinned:!!v?.pinned,archived:!!v?.archived,color:v?.color||'#ffffff',recurrence:v?.recurrence||'none',reminder:v?.reminder||'',links:Array.isArray(v?.links)?v.links:[],dependencies:Array.isArray(v?.dependencies)?v.dependencies:[]}; }
}
